# Generated by Django 5.2.15 on 2026-07-24 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('adress', models.CharField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='fbi', max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='bank.client')),
            ],
        ),
    ]
