# Generated by Django 5.2.15 on 2026-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_add_client_to_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('MAD', 'MAD'), ('FBI', 'FBI')], default='USD', max_length=3),
        ),
    ]
