# Generated by Django 5.2.15 on 2026-07-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='bank.wallet')),
                ('source_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='bank.wallet')),
            ],
        ),
    ]
